import {
  AreaChart,
  BasicDoubleYChart,
  BasicFunnelChart,
  BasicGaugeChart,
  BasicRichText,
  BasicScatterChart,
  ClusterBarChart,
  ClusterColumnChart,
  DoughnutChart,
  LineChart,
  MingXiTableChart,
  NormalOutlineMapChart,
  PercentageStackBarChart,
  PercentageStackColumnChart,
  PieChart,
  PivotSheetChart,
  RoseChart,
  ScatterOutlineMapChart,
  Scorecard,
  StackAreaChart,
  StackBarChart,
  StackColumnChart,
  WaterfallChart,
  WordCloudChart,
} from 'app/components/ChartGraph';
import { IChart } from 'app/types/Chart';

export const createBuiltinLegacyCharts = (): IChart[] => [
  new MingXiTableChart(),
  new PivotSheetChart(),
  new Scorecard(),
  new ClusterColumnChart(),
  new ClusterBarChart(),
  new StackColumnChart(),
  new StackBarChart(),
  new PercentageStackColumnChart(),
  new PercentageStackBarChart(),
  new WaterfallChart(),
  new LineChart(),
  new AreaChart(),
  new StackAreaChart(),
  new BasicScatterChart(),
  new PieChart(),
  new DoughnutChart(),
  new RoseChart(),
  new BasicFunnelChart(),
  new BasicDoubleYChart(),
  new WordCloudChart(),
  new NormalOutlineMapChart(),
  new ScatterOutlineMapChart(),
  new BasicGaugeChart(),
  new BasicRichText(),
];

export default createBuiltinLegacyCharts;
