import { lighten, rgba } from 'polished';
import {
  BLACK,
  BLUE,
  DG10,
  DG20,
  DG30,
  DG40,
  DG50,
  DG60,
  DG70,
  DG80,
  DG90,
  ERROR,
  G10,
  G20,
  G30,
  G40,
  G50,
  G60,
  G70,
  G80,
  G90,
  GREEN,
  HIGHLIGHT,
  INFO,
  NORMAL,
  ORANGE,
  PRIMARY,
  PROCESSING,
  RED,
  SUCCESS,
  WARNING,
  WHITE,
  YELLOW,
} from '../StyleConstants';
import { lensDark, lensLight } from '../lensTokens';

const common = {
  primary: PRIMARY,
  info: INFO,
  success: SUCCESS,
  processing: PROCESSING,
  error: ERROR,
  highlight: HIGHLIGHT,
  warning: WARNING,
  normal: NORMAL,

  blue: BLUE,
  green: GREEN,
  orange: ORANGE,
  yellow: YELLOW,
  red: RED,
  white: WHITE,
  black: BLACK,
};

const lightTheme = {
  bodyBackground: lensLight.canvas,
  componentBackground: lensLight.surface,
  emphasisBackground: lensLight.brandSoft,
  highlightBackground: lensLight.surfaceHover,
  textColor: lensLight.text,
  textColorSnd: lensLight.textSecondary,
  textColorLight: lensLight.textTertiary,
  textColorDisabled: lensLight.textTertiary,
  iconColorHover: rgba(BLACK, 0.75),
  borderColorBase: lensLight.borderStrong,
  borderColorEmphasis: lensLight.borderStrong,
  borderColorSplit: lensLight.border,
  shadow1: `0 1px 3px 0 ${rgba(lighten(0.15, BLACK), 0.1)}`,
  shadow2: `0 4px 16px 0 ${rgba(lighten(0.15, BLACK), 0.12)}`,
  shadow3: `0 12px 32px 0 ${rgba(lighten(0.15, BLACK), 0.16)}`,
  shadowSider: `0px 0 32px 0px ${rgba(G70, 0.075)}`,
  shadowBlock: `0px 0 32px 0px ${rgba(G70, 0.025)}`,
  ...common,
  primary: lensLight.brand,
  processing: lensLight.brand,
};

const darkTheme: Theme = {
  bodyBackground: lensDark.canvas,
  componentBackground: lensDark.surface,
  emphasisBackground: lensDark.brandSoft,
  highlightBackground: lensDark.surfaceHover,
  textColor: lensDark.text,
  textColorSnd: lensDark.textSecondary,
  textColorLight: lensDark.textTertiary,
  textColorDisabled: lensDark.textTertiary,
  iconColorHover: DG70,
  borderColorBase: lensDark.borderStrong,
  borderColorEmphasis: lensDark.borderStrong,
  borderColorSplit: lensDark.border,
  shadow1: `0 1px 5px 0 ${rgba(BLACK, 0.1)}`,
  shadow2: `0 6px 18px 0 ${rgba(BLACK, 0.4)}`,
  shadow3: `0 10px 32px 0 ${rgba(BLACK, 0.54)}`,
  shadowSider: 'none',
  shadowBlock: 'none',
  ...common,
  primary: lensDark.brand,
  processing: lensDark.brand,
};

export type Theme = typeof lightTheme;

export const themes = {
  light: lightTheme,
  dark: darkTheme,
};
